// @flow
export const QUESTIONS_FETCH_REQUESTED: string = 'QUESTIONS_FETCH_REQUESTED';
export const QUESTIONS_FETCH_SUCCESS: string = 'QUESTIONS_FETCH_SUCCESS';
export const QUESTIONS_FETCH_FAILURE: string = 'QUESTION_FETCH_FAILURE';
